// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTpKphY2fKnlDxpLrZoBpXLoWKOluihqo',
    appId: '1:581574614677:web:acd73b2ecd851d1730859c',
    messagingSenderId: '581574614677',
    projectId: 'venuelock-35a5a',
    authDomain: 'venuelock-35a5a.firebaseapp.com',
    storageBucket: 'venuelock-35a5a.firebasestorage.app',
    measurementId: 'G-0XN3X1VLLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhqhoVZNiOJxuN0uCz_M86eEfwxvQc0qY',
    appId: '1:581574614677:android:2da7d9cd25e9937730859c',
    messagingSenderId: '581574614677',
    projectId: 'venuelock-35a5a',
    storageBucket: 'venuelock-35a5a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4v3PGd0JP1-QY3dTtIO9C75HFh1zXA34',
    appId: '1:581574614677:ios:9772a599fc96af0030859c',
    messagingSenderId: '581574614677',
    projectId: 'venuelock-35a5a',
    storageBucket: 'venuelock-35a5a.firebasestorage.app',
    androidClientId: '581574614677-5sr27jpruqlhvdpb1uuqb5i06p8777kk.apps.googleusercontent.com',
    iosClientId: '581574614677-p1nmc7bek15s5irddjbk3aij76vnf9t0.apps.googleusercontent.com',
    iosBundleId: 'com.example.venueLockV1',
  );
}
